### ISSUE TITLE
Electron app freezes

### ISSUE THREAD

**Issue by mixmixmix** [road86/bahis-desk#65]
Common occurence, very random the windows window says "not responding" for a while.
Iko just had this while logging in and I've seen that it was happening between (succesful) queries to the server.

**Comment by ChasNelson1990** [comment]
Yes, this is a very common occurrence.
I _think_ (imagine mega italics there) that this is caused by all the ipc messaging being synchronous and not asynchronous and something, somewhere is stealing the main worker... and hanging...
Orrrrr... somewhere the main worker is trying to spin up another worker... that spinning up is failing and so the main worker is hanging whilst waiting for the "I am a new worker and I spun up fine" message that I presume it sends...

**Comment by mixmixmix** [comment]
@ChasNelson1990 Any note on how a server side changed https://github.com/road86/bahis-serve/pull/22 fixes electron app freezing?
